import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Monitoring Mahasiswa",
  description: "Generated by create next app",
  icon: "/monitoring-mhs-cumlaude/public/img/TULT.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizses="16x16" href="/favicon-16x16.png"></link>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
